services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: insider-one-champions-league:latest
    container_name: insider-one-champions-league-app-by-md
    ports:
      - "8080:8080"
    environment:
      APP_NAME: Insider One Champions League by MD
      APP_ENV: production
      APP_DEBUG: "false"
      APP_URL: https://insider-one-champions-league-project-by.onrender.com
      APP_KEY: ${APP_KEY:-}
      DB_CONNECTION: sqlite
      DB_DATABASE: /sqlite/database.sqlite
    volumes:
      - sqlite_data:/sqlite

volumes:
  sqlite_data:
